#File name: hxs.py
#Python version: 3.0
#Date started: October 2, 2017
#Development: https://github.com/HXS-API/Server/new/master/Codebase
#Learn more about HXS: https://github.com/HXS-API
#Contact: hxs@beehive.ngo

#URL Generator Module
'''The URL Generator's job:
Either scrape IATI or use IATI's API to identify and list all IATI file URLs,
Make the list available to the Extractor Module,
Separately, store an updated list in an internal database for internal and public access.
Learn more: https://github.com/HumanitarianExchangeServer/HXS-Codebase/wiki/URL-Generator
'''

#Extractor Module
'''The Extractor's job:
Navigate to each listed file location,
Scrape and combine each file's XML into one single XML code block,
Make the XML code block available to the Databaser Module,
Separately, date and store the block in an internal database for internal and public access.
Learn more: https://github.com/HumanitarianExchangeServer/HXS-Codebase/wiki/Extractor
'''

#Databaser Module
'''The Databaser's job:
Line-by-line traverse through the XML code block generated by the Extractor,
Match XML elements and create and update nodes and relationships in the master database,
Log unmatched XML elements and unrecognizable fields.
Learn more: https://github.com/HumanitarianExchangeServer/HXS-Codebase/wiki/Databaser
'''

#automoator Module
'''The Automator's job:
Run the modules on a regular, defined schedule, keeping the database up-to-date.
Learn more: https://github.com/HumanitarianExchangeServer/HXS-Codebase/wiki/Automator
'''
